enum Inputs {
  EMAIL,
  PASSWORD,
  REPEAT_PASSWORD,
  FIRST_NAME,
  LAST_NAME,
  DATE_OF_BIRTH,
  SHIPPING_STREET,
  SHIPPING_CITY,
  SHIPPING_POSTAL,
  SHIPPING_COUNTRY,
  BILLING_STREET,
  BILLING_CITY,
  BILLING_POSTAL,
  BILLING_COUNTRY,
}

export default Inputs;
