enum EventName {
  LOGIN,
  LOGOUT,
  IMAGES_LOADED_TO_PRODUCT_PAGE,
  ADDRESS_CHANGED,
  SHOW_FILTER,
  UPDATE_CATALOG_CARDS,
  UPDATE_FILTER_TAGS,
  ADDRESS_ADDED,
  UPDATE_CART,
  TOTAL_COST_CHANGED,
  SPINNER_SHOW,
  SPINNER_HIDE,
  ADD_TO_CART,
  REMOVE_FROM_CART,
}

export default EventName;
